version: '3.8'

services:
  persona:
    build:
      context: ./personas
      dockerfile: Dockerfile.dev
    volumes:
      - ./personas:/app
      - /app/node_modules
    command: ts-node-dev --respawn --transpile-only src/main.ts

  historial:
    build:
      context: ./historial
      dockerfile: Dockerfile.dev
    volumes:
      - ./historial:/app
      - /app/target
    command: ./mvnw spring-boot:run
